### ISSUE TITLE
navigation macro not work for system tiddler

### ISSUE THREAD

**Issue by oeyoews** [kookma/TW-Utility#2]
This [simple navigation](https://github.com/kookma/TW-Utility/blob/master/source/utility/macros/simple-navigation.tid) macro seems to have no effect on the system tiddler of the plugin. When I change the system tiddler to shadow, it can work normally. What is the reason?

**Comment by oeyoews** [comment]
[test link](https://neotw.netlify.app/#%24%3A%2Fplugins%2Foeyoews%2Ftiddlywiki-random-tip%2Fdocs%2Fcn-tw)

**Comment by oeyoews** [comment]
According to the tiddlywiki documentation, the tags here only work with non-system tiddlers

**Comment by kookma** [comment]
That's true!
