### ISSUE TITLE
Icon layout error

### ISSUE THREAD

**Issue by straywriter** [kookma/TW-Utility#4]
![image](https://github.com/kookma/TW-Utility/assets/48555863/59d8dacf-55fa-445f-ab7c-019cc27130e1)
![image](https://github.com/kookma/TW-Utility/assets/48555863/6b90b2b0-86f0-43e3-a1c6-d995a6fddbab)

It should be written like this

**Comment by kookma** [comment]
This is related to favorites plugin!
A new version pushed and fixed the issue!
