### ISSUE TITLE
source-toggle-button should not use cascade

### ISSUE THREAD

**Issue by linonetwo** [kookma/TW-Utility#5]
![图片](https://github.com/user-attachments/assets/be40530b-3a4f-4612-a300-e26b579106ea)

Otherwise you will block cascaded that below yours.

I think this kind of feature should use traditional viewtemplate tag + conditional shortcut to add. Because it don't need to "block" whole body. It should just add new things to the body.

**Comment by kookma** [comment]
But this is true for all Cascades. The Utility cascades comes just before default template!

You can use the `$:/tags/ViewTemplateBodyFilter` to reorder the ViewTemplateBodyFilters.
The issue is with other custom plugins. Any other plugin can cause such problem.

**Comment by linonetwo** [comment]
Jeremy recommend use old way when possible https://github.com/TiddlyWiki/TiddlyWiki5/issues/8489#issuecomment-2270863185

so I'm not using cascade too https://github.com/TiddlyWiki/TiddlyWiki5/pull/8505

**Comment by kookma** [comment]
The reason I use Cascades here is I have other plugins use cascades or view Template segment (like smart tabs) and arranging them is difficult. So here I prefer to use Cascades to make sure Source button comes with body! and all other like Node Explorer come after.

**Comment by linonetwo** [comment]
Well, you can use list-after body with view Template segment.

I think that is why somethings I don't see the source button. And is hard to debug why, because there is no https://github.com/TiddlyWiki/TiddlyWiki5/issues/8489 yet.

**Comment by linonetwo** [comment]
Cascades means replace, while view Template segment means append. While we can do appeld by replace. Maybe I can add this to the tw doc, I just learn this.

I'm not saying we must do this, just a suggesstion.

**Comment by kookma** [comment]
Thank you @linonetwo 
If you put the Utility Cascade just before $:/config/ViewTemplateTitleFilters/default it will always work with no problem.
By the way I note this idea and will comeback after some more experiments with new kookma plugins!

**Comment by kookma** [comment]
> list-after body

unfortunately, this does not work as expected. assume several plugins use `list-after: $:/core/ui/ViewTemplate/title/default` then which plugin will win? 
So, always we have to manually rearrange the view templates to get the correct results.

**Comment by linonetwo** [comment]
I see, unless it use the priority field, which needs extra handling in the core, not only sort[].

**Comment by kookma** [comment]
@linonetwo 
As per your request I reverted the source code toggle button from Cascades to segment ViewTemplate.
I decided to use Cascades when the whole body is changed and segment viewtemplate when a new segment is added to tiddler.
See Revision 3.0.1

**Comment by linonetwo** [comment]
Thank you, don't know why but before this I haven't seem the "source code toggle button" for a while...

**Comment by linonetwo** [comment]
> use Cascades when the whole body is changed and segment viewtemplate when a new segment is added to tiddler.

I think that is exactly what Jeremy means in https://github.com/TiddlyWiki/TiddlyWiki5/issues/8489#issuecomment-2270863185

**Comment by kookma** [comment]
> Thank you, don't know why but before this I haven't seem the "source code toggle button" for a while...

Does everything work for you now?

**Comment by linonetwo** [comment]
Yes, it works now.
