### ISSUE TITLE
[3.0] Source is missing on sectionized tiddlers

### ISSUE THREAD

**Issue by Vingolf** [kookma/TW-Utility#6]
**Bug or Feature** 

I have realized that Utility 3.0 does not show **Source** on sectionized tiddlers.

In Utility 2.x (i.e 2.7.0)  **Code** is shown on sectionized tiddlers.

Is this behavior intentional
or are there settings to add **Source** to sectioned tiddlers as well?

Vingolf

**Comment by kookma** [comment]
I am afraid I do noy follow you. Would you please attach an example or explain in more detail?

A difference in Utility 3 and 2.x is the later use viewTemplate, but the new Utility 3 uses Cascades.

**Comment by Vingolf** [comment]
> Would you please attach an example or explain in more detail?

I'm sorry Mohammad, I describe the issue in more detail:

**Describe the bug**
In a tiddler that is divided into sections with Section Editor, the Utility 3.0 plugin
does not display a **Source** below the tiddler.

**To Reproduce**

 * Use a wiki with following plugins installed: 

1. Tiddlywiki Core 5.3.5 
2. Section Editor 1.2.2
3. Utility Plugin 3.0 
3.1 Settings:  Show **source** botton on the tiddlers (with no filters)

4. Create a **New Tidder**
4.1 **Source** is shown below the tiddler

5. Add field: se-type 
5.1 **Source** below the tiddler vanishes

**Expected behavior**
Compared with previous version I have at hand:
* Tiddlywiki Core 5.3.3
* Utility Plugin 2.7.0 
* Section Editor 1.2.1

**Code** is shown even below a sectionized tiddler.

Vingolf

**Comment by kookma** [comment]
Thank you. I will investigate and return to you!

Best

**Comment by kookma** [comment]
I found the reason of this issue. Both Utility 3 and Section editor use Cascades. So I have to decide and revert one of the plugin to use old style viewtemplate.
Fix will come, but please use the older version of Utility until proper decision made.

**Comment by kookma** [comment]
Update 3.0.1 fixed this issue.
